# Auto-generated by IDE. Any changes made by user will be lost!
BASEDIR =  $$quote($$_PRO_FILE_PWD_)

device {
    CONFIG(debug, debug|release) {
        SOURCES +=  $$quote($$BASEDIR/src/Searcher.cpp) \
                 $$quote($$BASEDIR/src/VimeoAuth.cpp) \
                 $$quote($$BASEDIR/src/VimeoManager.cpp) \
                 $$quote($$BASEDIR/src/applicationui.cpp) \
                 $$quote($$BASEDIR/src/main.cpp) \
                 $$quote($$BASEDIR/src/oauth/kqoauth2request.cpp) \
                 $$quote($$BASEDIR/src/oauth/kqoauthauthreplyserver.cpp) \
                 $$quote($$BASEDIR/src/oauth/kqoauthmanager.cpp) \
                 $$quote($$BASEDIR/src/oauth/kqoauthrequest.cpp) \
                 $$quote($$BASEDIR/src/oauth/kqoauthrequest_1.cpp) \
                 $$quote($$BASEDIR/src/oauth/kqoauthrequest_xauth.cpp) \
                 $$quote($$BASEDIR/src/oauth/kqoauthutils.cpp)

        HEADERS +=  $$quote($$BASEDIR/src/Searcher.hpp) \
                 $$quote($$BASEDIR/src/VimeoAuth.h) \
                 $$quote($$BASEDIR/src/VimeoManager.h) \
                 $$quote($$BASEDIR/src/applicationui.hpp) \
                 $$quote($$BASEDIR/src/oauth/kqoauth2request.h) \
                 $$quote($$BASEDIR/src/oauth/kqoauth2request_p.h) \
                 $$quote($$BASEDIR/src/oauth/kqoauthauthreplyserver.h) \
                 $$quote($$BASEDIR/src/oauth/kqoauthauthreplyserver_p.h) \
                 $$quote($$BASEDIR/src/oauth/kqoauthglobals.h) \
                 $$quote($$BASEDIR/src/oauth/kqoauthmanager.h) \
                 $$quote($$BASEDIR/src/oauth/kqoauthmanager_p.h) \
                 $$quote($$BASEDIR/src/oauth/kqoauthrequest.h) \
                 $$quote($$BASEDIR/src/oauth/kqoauthrequest_1.h) \
                 $$quote($$BASEDIR/src/oauth/kqoauthrequest_p.h) \
                 $$quote($$BASEDIR/src/oauth/kqoauthrequest_xauth.h) \
                 $$quote($$BASEDIR/src/oauth/kqoauthrequest_xauth_p.h) \
                 $$quote($$BASEDIR/src/oauth/kqoauthutils.h)
    }

    CONFIG(release, debug|release) {
        SOURCES +=  $$quote($$BASEDIR/src/Searcher.cpp) \
                 $$quote($$BASEDIR/src/VimeoAuth.cpp) \
                 $$quote($$BASEDIR/src/VimeoManager.cpp) \
                 $$quote($$BASEDIR/src/applicationui.cpp) \
                 $$quote($$BASEDIR/src/main.cpp) \
                 $$quote($$BASEDIR/src/oauth/kqoauth2request.cpp) \
                 $$quote($$BASEDIR/src/oauth/kqoauthauthreplyserver.cpp) \
                 $$quote($$BASEDIR/src/oauth/kqoauthmanager.cpp) \
                 $$quote($$BASEDIR/src/oauth/kqoauthrequest.cpp) \
                 $$quote($$BASEDIR/src/oauth/kqoauthrequest_1.cpp) \
                 $$quote($$BASEDIR/src/oauth/kqoauthrequest_xauth.cpp) \
                 $$quote($$BASEDIR/src/oauth/kqoauthutils.cpp)

        HEADERS +=  $$quote($$BASEDIR/src/Searcher.hpp) \
                 $$quote($$BASEDIR/src/VimeoAuth.h) \
                 $$quote($$BASEDIR/src/VimeoManager.h) \
                 $$quote($$BASEDIR/src/applicationui.hpp) \
                 $$quote($$BASEDIR/src/oauth/kqoauth2request.h) \
                 $$quote($$BASEDIR/src/oauth/kqoauth2request_p.h) \
                 $$quote($$BASEDIR/src/oauth/kqoauthauthreplyserver.h) \
                 $$quote($$BASEDIR/src/oauth/kqoauthauthreplyserver_p.h) \
                 $$quote($$BASEDIR/src/oauth/kqoauthglobals.h) \
                 $$quote($$BASEDIR/src/oauth/kqoauthmanager.h) \
                 $$quote($$BASEDIR/src/oauth/kqoauthmanager_p.h) \
                 $$quote($$BASEDIR/src/oauth/kqoauthrequest.h) \
                 $$quote($$BASEDIR/src/oauth/kqoauthrequest_1.h) \
                 $$quote($$BASEDIR/src/oauth/kqoauthrequest_p.h) \
                 $$quote($$BASEDIR/src/oauth/kqoauthrequest_xauth.h) \
                 $$quote($$BASEDIR/src/oauth/kqoauthrequest_xauth_p.h) \
                 $$quote($$BASEDIR/src/oauth/kqoauthutils.h)
    }
}

simulator {
    CONFIG(debug, debug|release) {
        SOURCES +=  $$quote($$BASEDIR/src/Searcher.cpp) \
                 $$quote($$BASEDIR/src/VimeoAuth.cpp) \
                 $$quote($$BASEDIR/src/VimeoManager.cpp) \
                 $$quote($$BASEDIR/src/applicationui.cpp) \
                 $$quote($$BASEDIR/src/main.cpp) \
                 $$quote($$BASEDIR/src/oauth/kqoauth2request.cpp) \
                 $$quote($$BASEDIR/src/oauth/kqoauthauthreplyserver.cpp) \
                 $$quote($$BASEDIR/src/oauth/kqoauthmanager.cpp) \
                 $$quote($$BASEDIR/src/oauth/kqoauthrequest.cpp) \
                 $$quote($$BASEDIR/src/oauth/kqoauthrequest_1.cpp) \
                 $$quote($$BASEDIR/src/oauth/kqoauthrequest_xauth.cpp) \
                 $$quote($$BASEDIR/src/oauth/kqoauthutils.cpp)

        HEADERS +=  $$quote($$BASEDIR/src/Searcher.hpp) \
                 $$quote($$BASEDIR/src/VimeoAuth.h) \
                 $$quote($$BASEDIR/src/VimeoManager.h) \
                 $$quote($$BASEDIR/src/applicationui.hpp) \
                 $$quote($$BASEDIR/src/oauth/kqoauth2request.h) \
                 $$quote($$BASEDIR/src/oauth/kqoauth2request_p.h) \
                 $$quote($$BASEDIR/src/oauth/kqoauthauthreplyserver.h) \
                 $$quote($$BASEDIR/src/oauth/kqoauthauthreplyserver_p.h) \
                 $$quote($$BASEDIR/src/oauth/kqoauthglobals.h) \
                 $$quote($$BASEDIR/src/oauth/kqoauthmanager.h) \
                 $$quote($$BASEDIR/src/oauth/kqoauthmanager_p.h) \
                 $$quote($$BASEDIR/src/oauth/kqoauthrequest.h) \
                 $$quote($$BASEDIR/src/oauth/kqoauthrequest_1.h) \
                 $$quote($$BASEDIR/src/oauth/kqoauthrequest_p.h) \
                 $$quote($$BASEDIR/src/oauth/kqoauthrequest_xauth.h) \
                 $$quote($$BASEDIR/src/oauth/kqoauthrequest_xauth_p.h) \
                 $$quote($$BASEDIR/src/oauth/kqoauthutils.h)
    }
}

INCLUDEPATH +=  $$quote($$BASEDIR/src/oauth) \
         $$quote($$BASEDIR/src)

CONFIG += precompile_header

PRECOMPILED_HEADER =  $$quote($$BASEDIR/precompiled.h)

lupdate_inclusion {
    SOURCES +=  $$quote($$BASEDIR/../src/*.c) \
             $$quote($$BASEDIR/../src/*.c++) \
             $$quote($$BASEDIR/../src/*.cc) \
             $$quote($$BASEDIR/../src/*.cpp) \
             $$quote($$BASEDIR/../src/*.cxx) \
             $$quote($$BASEDIR/../assets/*.qml) \
             $$quote($$BASEDIR/../assets/*.js) \
             $$quote($$BASEDIR/../assets/*.qs)

    HEADERS +=  $$quote($$BASEDIR/../src/*.h) \
             $$quote($$BASEDIR/../src/*.h++) \
             $$quote($$BASEDIR/../src/*.hh) \
             $$quote($$BASEDIR/../src/*.hpp) \
             $$quote($$BASEDIR/../src/*.hxx)
}

TRANSLATIONS =  $$quote($${TARGET}.ts)
